counter:
  energy_reset_days:
    initial: 0
    restore: true
    step: 1
    minimum: 0
    maximum: 65535

utility_meter:
  bimonthly_energy:
    source: sensor.total_power

sensor:
  - platform: template
    sensors:
      kwh_cost:
        value_template: >
          {% if now().month in [6,7,8,9] %}
            {% if states("sensor.bimonthly_energy") | float < 240 %}
              {{1.68}}
            {% elif states("sensor.bimonthly_energy") | float >= 240  and states("sensor.bimonthly_energy") | float < 660 %}
              {{2.45}}
            {% elif states("sensor.bimonthly_energy") | float >= 660  and states("sensor.bimonthly_energy") | float < 1000 %}
              {{3.7}}
            {% elif states("sensor.bimonthly_energy") | float >= 1000  and states("sensor.bimonthly_energy") | float < 1400 %}
              {{5.04}}
            {% elif states("sensor.bimonthly_energy") | float >= 1400  and states("sensor.bimonthly_energy") | float < 2000 %}
              {{6.24}}
            {% elif states("sensor.bimonthly_energy") | float >= 2000 %}
              {{8.46}}
            {% endif %}
          {% else %}
            {% if states("sensor.bimonthly_energy") | float < 240 %}
              {{1.68}}
            {% elif states("sensor.bimonthly_energy") | float >= 240  and states("sensor.bimonthly_energy") | float < 660 %}
              {{2.16}}
            {% elif states("sensor.bimonthly_energy") | float >= 660  and states("sensor.bimonthly_energy") | float < 1000 %}
              {{3.03}}
            {% elif states("sensor.bimonthly_energy") | float >= 1000  and states("sensor.bimonthly_energy") | float < 1400 %}
              {{4.14}}
            {% elif states("sensor.bimonthly_energy") | float >= 1400  and states("sensor.bimonthly_energy") | float < 2000 %}
              {{5.07}}
            {% elif states("sensor.bimonthly_energy") | float >= 2000 %}
              {{6.63}}
            {% endif %}
          {% endif %}
        friendly_name: "目前電度單價"
        unit_of_measurement: "TWD/kWh"
        device_class: monetary

  - platform: template
    sensors:
      power_cost:
        value_template: >
          {% if now().month in [6,7,8,9] %}
            {% if states("sensor.bimonthly_energy") | float < 240 %}
              {{(states("sensor.bimonthly_energy") | float * states("sensor.kwh_cost") | float) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 240  and states("sensor.bimonthly_energy") | float < 660 %}
              {{(((states("sensor.bimonthly_energy") | float - 240) * states("sensor.kwh_cost") | float) + 403.2) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 660  and states("sensor.bimonthly_energy") | float < 1000 %}
              {{(((states("sensor.bimonthly_energy") | float - 660) * states("sensor.kwh_cost") | float) + 1432.2) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 1000  and states("sensor.bimonthly_energy") | float < 1400 %}
              {{(((states("sensor.bimonthly_energy") | float - 1000) * states("sensor.kwh_cost") | float) + 2690.2) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 1400  and states("sensor.bimonthly_energy") | float < 2000 %}
              {{(((states("sensor.bimonthly_energy") | float - 1400) * states("sensor.kwh_cost") | float) + 4706.2) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 2000 %}
              {{(((states("sensor.bimonthly_energy") | float - 2000) * states("sensor.kwh_cost") | float) + 8450.2) | round(0)}}
            {% endif %}
          {% else %}
            {% if states("sensor.bimonthly_energy") | float < 240 %}
              {{(states("sensor.bimonthly_energy") | float * states("sensor.kwh_cost") | float) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 240  and states("sensor.bimonthly_energy") | float < 660 %}
              {{(((states("sensor.bimonthly_energy") | float - 240) * states("sensor.kwh_cost") | float) + 403.2) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 660  and states("sensor.bimonthly_energy") | float < 1000 %}
              {{(((states("sensor.bimonthly_energy") | float - 660) * states("sensor.kwh_cost") | float) + 1310.4) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 1000  and states("sensor.bimonthly_energy") | float < 1400 %}
              {{(((states("sensor.bimonthly_energy") | float - 1000) * states("sensor.kwh_cost") | float) + 2340.6) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 1400  and states("sensor.bimonthly_energy") | float < 2000 %}
              {{(((states("sensor.bimonthly_energy") | float - 1400) * states("sensor.kwh_cost") | float) + 3996.6) | round(0)}}
            {% elif states("sensor.bimonthly_energy") | float >= 2000 %}
              {{(((states("sensor.bimonthly_energy") | float - 2000) * states("sensor.kwh_cost") | float) + 7038.6) | round(0)}}
            {% endif %}
          {% endif %}
        friendly_name: "目前總電費"
        unit_of_measurement: "TWD"
        device_class: monetary

  - platform: integration
    source: sensor.your_W_sensor # 這是您的用電 "W (瓦特)" 偵測器
    name: total_power
    unit_prefix: k
    method: right
    round: 3
